CREATE TABLE IF NOT EXISTS documents(
	url STRING PRIMARY KEY NOT NULL,
	content STRING NOT NULL,
	timeMillis INT NOT NULL,
	indexTimeMillis INT NOT NULL DEFAULT 0,
	counter INT NOT NULL
);
-- TODO: add rank

CREATE TABLE IF NOT EXISTS urlstore_queue(
	url STRING PRIMARY KEY NOT NULL
);

CREATE TABLE IF NOT EXISTS keywords(
	word STRING PRIMARY KEY NOT NULL
);

CREATE TABLE IF NOT EXISTS keywords_documents(
	docID INT NOT NULL,
	wordID INT NOT NULL,
	PRIMARY KEY (docID, wordID),
	FOREIGN KEY (docID) REFERENCES documents(ROWID)
		ON UPDATE CASCADE
		ON DELETE CASCADE,
	FOREIGN KEY (wordID) REFERENCES keywords(ROWID)
		ON UPDATE CASCADE
		ON DELETE CASCADE
);
